### PR TITLE
used location.protocol + "//" for io.connect instead of "http://" to …

### PR DESCRIPTION
**Pull request by jaapvandenhandel**
I use an nginx reverse proxy to tunnel the web_app through https. But then the websockets don't work anymore.
This fixes that.
Do you want to incorporate this change?

### CODE REVIEW

**Comment by Stefal** [comment]
Hi!
If location.protocol is better than http (I'll investigate) Yes, I will merge your change with pleasure.

 Could you edit your PR to merge it to the dev branch?

**Comment by Stefal** [comment]
Is this nginx config example another way to do what you want ? https://github.com/Stefal/rtkbase/commit/154260fea054559a86897a104f43b3655efa9e3c

**Comment by jaapvandenhandel** [comment]
Thanks, I changed the target branch. But now there are conflicts. 
I will just recreate it with dev as source branch

**Comment by Stefal** [comment]
Replaced with https://github.com/Stefal/rtkbase/pull/287

**Pull request closed without merging**
