### PR TITLE
used location.protocol + "//" for io.connect instead of "http://" to …

### PR DESCRIPTION
**Pull request by jaapvandenhandel**
I use an nginx reverse proxy to tunnel the web_app through https. But then the websockets don't work anymore.
This fixes that.

### CODE REVIEW

**Comment by Stefal** [comment]
Hi!
Could you try with
`socket = io.connect(namespace);`

It works on my test bed, and is even more simple.

**Comment by jaapvandenhandel** [comment]
Hi, 

Yes that also works on my setup.

**Comment by Stefal** [comment]
Thanks!

**Comment by jaapvandenhandel** [comment]
Your welcome. Thank you too

**Pull request merged**
