### PR TITLE
modify param fixed localisation

### PR DESCRIPTION
**Pull request by jancelin**

### CODE REVIEW

**Comment by Stefal** [comment]
"Fixed" compute mode ? I'm a little surprised because in this mode you need to enter the rover coordinates.

**Comment by jancelin** [comment]
argh... sorry it's static-start

**Comment by Stefal** [comment]
Static-start is a rover/base computation mode, and available only on the rtklibexplorer's fork... :)

**Comment by jancelin** [comment]
Well, we'll leave it as it was.

**Pull request closed without merging**
