### PR TITLE
create rinex tools

### PR DESCRIPTION
**Pull request by jancelin**

### CODE REVIEW

**Comment by iceberg1369** [comment]
it would be grate if convbin script could automatically detect raw data format.

**Comment by jancelin** [comment]
do you mean conversion from .zip or .ubx?

**Comment by iceberg1369** [comment]
@jancelin  we could use other oem rather than ublox. like novatel, tersus, etc. so its a good practice to announce the receiver oem in the convbin. ( could be configured in config file)

**Comment by jancelin** [comment]
OK @iceberg1369 I understand.
yes it's possible to add format detection from setting.conf

**Comment by Stefal** [comment]
Where is the best place to detect the receiver format? Inside the python app, or in the `convbin.sh` script?

My opinion: inside the python app.

**Comment by iceberg1369** [comment]
@Stefal yes. It is great to have this option in python app.

**Comment by Stefal** [comment]
It's ok now.
Maybe I could add an auto refresh on the table.

4k9w2vrf8s

**Comment by Stefal** [comment]
table refresh when we close the modal window.
ba7cc68bc69d135f98a807793f770320cddc37e9

**Comment by Stefal** [comment]
Merged!
Thanks @jancelin

**Pull request merged**
